Rails:
  Enabled: true
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
Rails/HasAndBelongsToMany:
  Enabled: false
Style/Documentation:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Metrics/AbcSize:
  Max: 20
AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'app/admin/**/*'
    - 'lib/tasks/*'
    - '**/Gemfile'
    - '**/Rakefile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'test/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'docs/**/*'
    - 'node_modules/**/*'
    - 'app/models/concerns/secure_token.rb'
